"IMAGE","FILE","TASK",ERROR"
"anchore/test_images:ubuntu-content-56d52bc","/usr/local/lib/python3.8/dist-packages/numpy.libs/libgfortran-2e0d59d6.so.5.0.0","unknowns-labeler","no package identified in executable file"
"anchore/test_images:ubuntu-content-56d52bc","/usr/local/lib/python3.8/dist-packages/numpy.libs/libopenblasp-r0-2d23e62b.3.17.so","unknowns-labeler","no package identified in executable file"
"anchore/test_images:ubuntu-content-56d52bc","/usr/local/lib/python3.8/dist-packages/numpy.libs/libquadmath-2d0c479f.so.0.0.0","unknowns-labeler","no package identified in executable file"
"anchore/test_images:ubuntu-content-56d52bc","/usr/local/lib/python3.8/dist-packages/numpy.libs/libz-eb09ad1d.so.1.2.3","unknowns-labeler","no package identified in executable file"
"anchore/test_images:ubuntu-content-56d52bc","/usr/local/lib/python3.8/dist-packages/numpy/core/_multiarray_tests.cpython-38-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"anchore/test_images:ubuntu-content-56d52bc","/usr/local/lib/python3.8/dist-packages/numpy/core/_multiarray_umath.cpython-38-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"anchore/test_images:ubuntu-content-56d52bc","/usr/local/lib/python3.8/dist-packages/numpy/core/_operand_flag_tests.cpython-38-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"anchore/test_images:ubuntu-content-56d52bc","/usr/local/lib/python3.8/dist-packages/numpy/core/_rational_tests.cpython-38-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"anchore/test_images:ubuntu-content-56d52bc","/usr/local/lib/python3.8/dist-packages/numpy/core/_simd.cpython-38-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"anchore/test_images:ubuntu-content-56d52bc","/usr/local/lib/python3.8/dist-packages/numpy/core/_struct_ufunc_tests.cpython-38-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"anchore/test_images:ubuntu-content-56d52bc","/usr/local/lib/python3.8/dist-packages/numpy/core/_umath_tests.cpython-38-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"anchore/test_images:ubuntu-content-56d52bc","/usr/local/lib/python3.8/dist-packages/numpy/fft/_pocketfft_internal.cpython-38-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"anchore/test_images:ubuntu-content-56d52bc","/usr/local/lib/python3.8/dist-packages/numpy/linalg/_umath_linalg.cpython-38-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"anchore/test_images:ubuntu-content-56d52bc","/usr/local/lib/python3.8/dist-packages/numpy/linalg/lapack_lite.cpython-38-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"anchore/test_images:ubuntu-content-56d52bc","/usr/local/lib/python3.8/dist-packages/numpy/random/_bounded_integers.cpython-38-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"anchore/test_images:ubuntu-content-56d52bc","/usr/local/lib/python3.8/dist-packages/numpy/random/_common.cpython-38-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"anchore/test_images:ubuntu-content-56d52bc","/usr/local/lib/python3.8/dist-packages/numpy/random/_generator.cpython-38-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"anchore/test_images:ubuntu-content-56d52bc","/usr/local/lib/python3.8/dist-packages/numpy/random/_mt19937.cpython-38-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"anchore/test_images:ubuntu-content-56d52bc","/usr/local/lib/python3.8/dist-packages/numpy/random/_pcg64.cpython-38-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"anchore/test_images:ubuntu-content-56d52bc","/usr/local/lib/python3.8/dist-packages/numpy/random/_philox.cpython-38-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"anchore/test_images:ubuntu-content-56d52bc","/usr/local/lib/python3.8/dist-packages/numpy/random/_sfc64.cpython-38-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"anchore/test_images:ubuntu-content-56d52bc","/usr/local/lib/python3.8/dist-packages/numpy/random/bit_generator.cpython-38-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"anchore/test_images:ubuntu-content-56d52bc","/usr/local/lib/python3.8/dist-packages/numpy/random/mtrand.cpython-38-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"anchore/test_images:ubuntu-content-56d52bc","/var/lib/dpkg/info/bash.preinst","unknowns-labeler","no package identified in executable file"
